version: "3.7"
services:
  app:
    build:
      args:
        user: Kyle
        uid: 1000
      context: ./
      dockerfile: Dockerfile.App
    image: ${APP_IMAGE_NAME}
    container_name: ${APP_CONTAINER_NAME}
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - SOW-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - laravel-volume:/docker-entrypoint-initdb.d
    networks:
      - SOW-network

  node:
    image: node:alpine
    build:
      context: ./
      dockerfile: Dockerfile.Node
    container_name: ${NODE_CONTAINER_NAME}
    user: "node"
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:alpine
    container_name: ${NGINX_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - SOW-network

volumes:
    laravel-volume:
        driver: local

networks:
  SOW-network:
    driver: bridge