version: '3.9'

services:
  web:
    image: nginx:latest
    container_name: SOW-nginx
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
      - db
      - node

  php-fpm:
    container_name: SOW-php
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html

  node:
    image: "node:alpine"
    container_name: SOW-node
    user: "node"
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    command: sh -c "npm install --legacy-peer-deps && 
              npm run build && npm run dev"

  db:
    image: mysql:8.0
    container_name: SOW-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d

networks:
    laravel:
        driver: bridge