version: "3.7"
services:
  app:
    build:
      args:
        user: Kyle
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: soul-of-wind
    container_name: Soul-of-Wind-Container
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - SOW-network
  db:
    image: mysql:8.0
    container_name: SOF-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - SOW-network
  nginx:
    image: nginx:alpine
    container_name: SOW-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - SOW-network
networks:
  SOW-network:
    driver: bridge