version: "3.7"
services:
  app:
    build:
      args:
        user: Kyle
        uid: 1000
      context: ./
      dockerfile: Dockerfile.app
    image: soul-of-wind
    container_name: SOW-container
    working_dir: /var/www/
    volumes:
      - ./:/var/www 
      - /var/www/vendor
    networks:
      - SOW-network
    depends_on:
      - db  
      - node
      - nginx
  db:
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - laravel-volume:/docker-entrypoint-initdb.d
    networks:
      - SOW-network

  node:
    build:
      context: ./
      dockerfile: Dockerfile.node
    image: node:alpine
    container_name: SOW-node
    working_dir: /var/www/
    ports:
      - 5173:5173
    environment:
      APP_URL: ${APP_URL}
    volumes:
      - ./:/var/www
      - /var/www/node_modules
  nginx:
    image: nginx:alpine
    container_name: ${NGINX_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - SOW-network 

volumes:
    laravel-volume:
        driver: local

networks:
  SOW-network:
    driver: bridge